### ISSUE TITLE
regex not working

### ISSUE THREAD

**Issue by miguel-cv** [brouberol/mashdown#1]
Hi!

Thank you for this useful project. For the videos of my interest it didn't find the start/end times of the songs, so I edited the regex, as some videos have the m:ss format (later mm:ss) ... and others have h:mm:ss ... a mess.

After fighting with regexes, i couldn't get extracted the hour (if it exists) without the ":", so i have to remove it later. 
With this regex you pick all:

```
TRACK_INFO = r"(?P<track_name>[^\n]+?)(?P<hours>(\d?):)?(?P<minutes>\d{1,2}):(?P<seconds>\d{2})"
```

...but you have to remove later the ":"

```
if groupdict['hours'] is None:
        groupdict['hours'] = 0
    else:
        groupdict['hours'] = groupdict['hours'].replace(':',"")
        groupdict['hours'] = int(groupdict['hours'])
```

Maybe its useful to someone.
P.S. Maybe something it's bad because i really don't know python.

**Comment by brouberol** [comment]
Could you make me a list of the real-life patterns you'd like to extract, and I could have a look during the weekend?

Edit: if you could also provide the youtube links associated with these patterns, that'd be even nicer.

Cheerio

**Comment by miguel-cv** [comment]
I send you a email with a couple of links.

**Comment by brouberol** [comment]
I've made the regex more tolerant (the trackname can be after or before the track time), and added some tests. Could you test this with the video links you sent me? I have a really crappy connection right now, so I can't really afford to wait 10h for the download to succeed.

Edit: to test this, you can checkout the "issue1" branch, and execute 

``` bash
$ python mashdown/main.py <youtube-url>
```

Cheers!

**Comment by miguel-cv** [comment]
Will try to test it tonight....Thanks!

**Comment by brouberol** [comment]
For the record, you sent me this by email, and I'm now merging our Github and email conversations:

> Error: [miguel@negro mashdown]$ python mashdown/main.py -m "Buckethead - Shadows Between the Sky.m4a" https://www.youtube.com/watch?v=oj6DBi264DI
> Fetching metadata for https://www.youtube.com/watch?v=oj6DBi264DI...
> Extracting track information...
> Traceback (most recent call last):
>   File "mashdown/main.py", line 102, in <module>
>     main()
>   File "mashdown/main.py", line 87, in main
>     tracks = tracklist(youtube_page.description)
> TypeError: tracklist() missing 1 required positional argument: 'tracklist_location'
> 
> I tested that youtube_page.description it's fetched "as is". Maybe my errors could be related to this?

``` bash
[miguel@negro mashdown]$ python -V
Python 3.4.3
```

I have tested the new code with both your pages, and they seem to work. I've merged the fix and tests to master and made a new release to PyPI.

**Comment by miguel-cv** [comment]
Thanks, updated through pip and working again. Sorry for delay answering.
